### ISSUE TITLE
Using electron supercluster eta or track eta

### ISSUE THREAD

**Issue by eyigitba** [UFLX2MuMu/Ntupliser#102]
I noticed that ttH is using `ele.superCluster()->position().eta()` and we are using `ele.eta()` to apply electron selection. Which one is more valid? Should we change the definition somewhere?

**Comment by eyigitba** [comment]
I ran some quick tests in data and MC. The difference between two etas look small, but it's there. What should we do?

ggH MC:
<img width="1120" alt="Screenshot 2019-11-28 at 11 30 01" src="https://user-images.githubusercontent.com/53942290/69798902-8aefd800-11d2-11ea-99fd-e48d2c2b9a1e.png">


data:
<img width="1052" alt="Screenshot 2019-11-28 at 11 29 28" src="https://user-images.githubusercontent.com/53942290/69798917-917e4f80-11d2-11ea-8db8-6e1af33407f4.png">

**Comment by bortigno** [comment]
Nice. I think we should use supercluster eta for the gap veto. It should be more efficient as it is a variable closer to the detector gap.

**Comment by eyigitba** [comment]
I will move our electron acceptance cut to apply on super cluster eta. I'll also add a float for scEta in our ntuples.

**Comment by eyigitba** [comment]
See 35860d8

**Comment by bortigno** [comment]
Merged
