### ISSUE TITLE
Fix 2016 crab config template to automatically change inputDBS

### ISSUE THREAD

**Issue by eyigitba** [UFLX2MuMu/Ntupliser#151]
This feature exists already in 2017 and 2018. We just need to change the relevant line from `global` to `DBS` (https://github.com/UFLX2MuMu/Ntupliser/blob/master_2016_94X/DiMuons/crab/templates/crab_config.py#L17). 

If the user doesn't specify a `DBS` name in `Samples.py` then we'll use `global`.

**Comment by zuoxunwu** [comment]
PR created. (#155 )

**Comment by eyigitba** [comment]
merged closing
