### ISSUE TITLE
Add inputDBS option to the latest 2016 samples

### ISSUE THREAD

**Issue by eyigitba** [UFLX2MuMu/Ntupliser#152]
We realized that the inputDBS option was not added to the privately produced 2016 samples. These samples need an option specifying that they exist in `phys03` and not on `global`. The relevant feature will also be implemented in crab config templates so that this is automatically handled. 

See #151

**Comment by zuoxunwu** [comment]
PR created for 2016 (#156 )

**Comment by zuoxunwu** [comment]
Another PR created for 2017 (#157 )

**Comment by eyigitba** [comment]
PRs merged closing
