### ISSUE TITLE
Move jet ID to tight in tuple making

### ISSUE THREAD

**Issue by bortigno** [UFLX2MuMu/Ntupliser#19]

**Comment by bortigno** [comment]
Add it as a variable in the ntuples

**Comment by abrinke1** [comment]
Also need to switch between 2016 and 2017 jet tight/loose ID definitions:
https://github.com/UFLX2MuMu/Ntupliser/blob/master/DiMuons/src/JetHelper.cc#L241

https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016

**Comment by bortigno** [comment]
Done in ce08189 .
