### ISSUE TITLE
implement mini-isolation

### ISSUE THREAD

**Issue by bortigno** [UFLX2MuMu/Ntupliser#41]
Implement mini-isolation for muons. Some inspirations from Andrea's code:

https://github.com/MiT-HEP/NeroProducer/blob/CMSSW_92X/Nero/src/NeroLeptons.cpp#L203
https://github.com/MiT-HEP/NeroProducer/blob/CMSSW_92X/Nero/src/MiniIsolation.cpp

**Comment by abrinke1** [comment]
Implemented functions "MuonCalcMiniIso" and "EleCalcMiniIso"

https://github.com/UFLX2MuMu/Ntupliser/blob/master_2017_94X/DiMuons/src/MuonHelper.cc#L487
https://github.com/UFLX2MuMu/Ntupliser/blob/master_2017_94X/DiMuons/src/EleHelper.cc#L199
